feat(sso): add domain configured for sso check before login
tchapgouv/tchap-web-v4 pull request #1131
Opened 2024-10-10 16:47 UTC by MarcWadai

fixes https://github.com/tchapgouv/tchap-web-v4/issues/1123

## Changes 
- Check sso flow available before going further

![image](https://github.com/user-attachments/assets/eedb7c26-b434-4ce3-9ba6-9f3992802990)

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md)).

2024-10-14 13:34 UTC, odelcroi commented
@areox-net  what do you think

2024-10-14 14:28 UTC, areox-net requested changes
Je pense qu'on peut changer le message en:
"ProConnect is not yet available for your domain"
"ProConnect n'est pas encore disponible pour votre domaine"

2024-10-14 14:29 UTC, areox-net commented
@odelcroi @MarcWadai J'ai suggéré un changement de phrase en rouge. 
Quel action on peut proposer à l'utilisateur? Il peut contacter quelqu'un pour activer l'SSO ?

2024-10-14 14:33 UTC, areox-net commented
En fait, je ne sais pas pour l'user c'est plus clair "pas disponible" ou "desactivé", et si le "pas encore" est utile

"ProConnect is disabled for your domain"
"ProConnect est désactivé pour votre domaine"

2024-10-15 09:41 UTC, MarcWadai commented
@areox-net  Dans la landing page on utilise le terme administration plutôt que domaine. Je pense que c'est peut être plus clair pour les agents publiques. 
Je pense que désactivé est plus juste que disponible, car ce n'est pas forcément un choix technique, mais potentiellement plus l'administration qui ne souhaite pas l'activé . Donc je dirais bien : 

"ProConnect is disabled for your administration"
"ProConnect est désactivé pour votre administration"

2024-10-15 14:14 UTC, areox-net commented
@MarcWadai Ok pour "desactivé".
Par contre pour "administration" je suis d'accord avec toi mais dans l'UI on parle que de domaine il me semble. C'est peut-etre une bonne idée de changer mais je propose qu'on le change partout avec un ticket dédié.

2024-10-15 15:36 UTC, MarcWadai commented
@areox-net c'est ok pour moi ! j'ai fait la modif comme ça (cf capture d'écran)

2024-10-15 16:17 UTC, areox-net approved these changes

2024-10-16 07:43 UTC, merged

2024-10-16 11:05 UTC, areox-net commented
@MarcWadai Je viens de m'en rendre compte, mais dans le cas de cet erreur le bouton PC ne devrait pas etre actif. On ne peut pas continuer.