UX improvements for XSSS
tchapgouv/tchap-web-v4 pull request #453
Opened 2023-03-09 10:33 UTC by aulamber

Cf. https://github.com/tchapgouv/tchap-web-v4/issues/442
and https://github.com/tchapgouv/tchap-web-v4/issues/451

Todos:

- [x] Change buttons "Configurer" and "Activer la sauvegarde automatique des messages" 
into "Activer"
- [x] Le texte au dessous de "Sauvegarde automatique des messages" devrait etre un générique:
"Cette fonction vous permet de sauvegarder automatiquement vos messages et de les récupérer à tout moment à l’aide d’un Code de récupération."

-> before:
<img width="495" alt="Screenshot 2023-03-14 at 15 05 14" src="https://user-images.githubusercontent.com/6305268/225026304-10b90fbf-e2fc-4c09-9015-ae8f3f1dc20d.png">

-> after: 
<img width="987" alt="Screenshot 2023-03-14 at 18 05 28" src="https://user-images.githubusercontent.com/6305268/225083077-fcd49ae8-598e-424f-8b84-45cf02ea51d8.png">

- [x] Change button "vérifiez" en "vérifier"

-> before
<img width="534" alt="Screenshot 2023-03-14 at 16 17 28" src="https://user-images.githubusercontent.com/6305268/225048150-d7d5fba0-58e1-465d-873f-49a94646db08.png">

-> after
<img width="668" alt="Screenshot 2023-03-14 at 17 59 52" src="https://user-images.githubusercontent.com/6305268/225083168-50bbf566-d934-41e9-832a-6e6456c877dc.png">

 - [x] Remove label "ou" and button "Envoyer"

-> before:
<img width="607" alt="Screenshot 2023-03-14 at 18 07 56" src="https://user-images.githubusercontent.com/6305268/225083629-7234e567-49e2-4a15-a4fe-8c0ca16f90d0.png">

-> after:
<img width="762" alt="Screenshot 2023-03-14 at 18 00 08" src="https://user-images.githubusercontent.com/6305268/225083447-7cfb93e2-ccf4-467e-9c35-a77c82641d42.png">

- [x]  both buttons "Configurer" and "Activer la sauvegarde automatique des messages" leads to the same dialog (sauvegarder votre clé de récupération). Yet they are not named the same way. Change to the name label "Activer".

-> before:
<img width="631" alt="Screenshot 2023-03-14 at 18 10 49" src="https://user-images.githubusercontent.com/6305268/225084342-72d009a5-aabe-4c91-b9f7-af69d1cbc734.png">

-> after:
<img width="987" alt="Screenshot 2023-03-14 at 18 05 28" src="https://user-images.githubusercontent.com/6305268/225084287-ebcef037-9856-4d25-9b41-704757cb09e3.png">

- [x] Instead of button "button "Connecter cette session à la sauvegarde des clés", have "Vérifier cette session"

-> before:
<img width="655" alt="Screenshot 2023-03-14 at 18 13 51" src="https://user-images.githubusercontent.com/6305268/225085066-9730c8cb-0ac7-47de-a47e-df361d8ed22a.png">

-> after:
<img width="889" alt="Screenshot 2023-03-14 at 18 01 22" src="https://user-images.githubusercontent.com/6305268/225084974-973f3a0a-1588-4003-977e-d71c9ddd1933.png">

2023-03-10 16:06 UTC, jdauphant commented on src/i18n/strings/tchap_translations.json
> +    "en" : "Activate your Recovery Code key to never lose your messages"
```suggestion
    "en" : "Activate your Recovery Code to never lose your messages"
```

2023-03-10 16:07 UTC, jdauphant commented on src/i18n/strings/tchap_translations.json
>      "en": "Store your Recovery Key key somewhere safe, like a password manager or a safe"
```suggestion
  "Store your Security Key somewhere safe, like a password manager or a safe, as it's used to safeguard your encrypted data.": {
    "fr": "Conservez votre code de récupération dans un endroit sûr, par exemple : votre gestionnaire de mot de passe sur un papier dans une armoire ou un tiroir fermé à clé.",
    "en": "Store your Recovery Codey somewhere safe, like a password manager or a safe"
```

2023-03-10 16:08 UTC, jdauphant commented on src/i18n/strings/tchap_translations.json
> +    "en": "A new Security Phrase and code for Secure Messages have been detected."
```suggestion
    "fr": "Un nouveau code de récupération pour les messages sécurisés ont été détectés.",
    "en": "A new Recovery Code for Secure Messages have been detected."
```

2023-03-10 16:10 UTC, jdauphant reviewed
@aulamber  J'ai relu et validé les textes, j'attends les captures d'écrans.

@Caroline-lawson @areox-net si vous voulez relire les textes

2023-03-10 16:16 UTC, areox-net commented on src/i18n/strings/tchap_translations.json
> +    "en": "A new Security Phrase and code for Secure Messages have been detected."
Un nouveau code de récupération pour les messages sécurisés **a été détecté**.

2023-03-10 16:17 UTC, areox-net commented on src/i18n/strings/tchap_translations.json
>      "en": "Store your Recovery Key key somewhere safe, like a password manager or a safe"
...par exemple : votre gestionnaire de mot de passe**,** sur un papier...

2023-03-13 13:51 UTC, Caroline-lawson commented on src/i18n/strings/tchap_translations.json
>      "en": "Store your Recovery Key key somewhere safe, like a password manager or a safe"
... **dans** votre gestionnaire de mot de passe...

2023-03-13 14:41 UTC, odelcroi requested changes

2023-03-13 14:41 UTC, odelcroi commented on patches/activate-cross-signing-and-secure-storage-react/matrix-react-sdk+3.63.0.patch
> ++            !TchapUIFeature.isCrossSigningAndSecureStorageActive){
not sure why there is a change here, isCrossSigningAndSecureStorageActive() seems to be correct

2023-03-13 14:41 UTC, odelcroi commented on patches/activate-cross-signing-and-secure-storage-react/matrix-react-sdk+3.63.0.patch
> ++        if (!TchapUIFeature.isCrossSigningAndSecureStorageActive) {
not sure why there is a change here, isCrossSigningAndSecureStorageActive() seems to be correct

2023-03-13 14:41 UTC, odelcroi commented on patches/activate-cross-signing-and-secure-storage-react/matrix-react-sdk+3.63.0.patch
> ++            if (!TchapUIFeature.isCrossSigningAndSecureStorageActive) {
not sure why there is a change here, isCrossSigningAndSecureStorageActive() seems to be correct

2023-03-13 14:41 UTC, odelcroi commented on src/i18n/strings/tchap_translations.json
> +    "fr": "Cette fonction vous permet de sauvegarder automatiquement vos messages et de les récupérer à tout moment à l’aide d’un Code de récupération."
d'un code -> du code

2023-03-13 14:41 UTC, odelcroi commented on src/i18n/strings/tchap_translations.json
> +    "fr": "Nous génèrerons un code de récupération que vous devrez stocker dans un endroit sûr, comme un gestionnaire de mots de passe ou un coffre.",
Nous génèrerons un code de récupération -> Nous génèrerons votre code de récupération @areox-net @Caroline-lawson thoughts?

2023-03-13 14:57 UTC, Caroline-lawson commented on src/i18n/strings/tchap_translations.json
> +    "fr": "Nous génèrerons un code de récupération que vous devrez stocker dans un endroit sûr, comme un gestionnaire de mots de passe ou un coffre.",
Votre code de récupération unique (because some users exchange Tchap Keys) ?

2023-03-14 11:29 UTC, areox-net approved these changes

2023-03-15 08:59 UTC, areox-net approved these changes

2023-03-15 11:36 UTC, odelcroi commented on patches/activate-cross-signing-and-secure-storage-react/matrix-react-sdk+3.63.0.patch
> +-            statusDescription = (
I would rather keep this text for the beta phase to be able to understand easily what is going on.

2023-03-15 11:39 UTC, odelcroi requested changes

2023-03-15 11:39 UTC, odelcroi commented on patches/activate-cross-signing-and-secure-storage-react/matrix-react-sdk+3.63.0.patch
> +-                statusDescription = (
I would rather keep this text for the beta phase to be able to understand easily what is going on.

2023-03-16 09:22 UTC, odelcroi requested changes

2023-03-16 09:22 UTC, odelcroi commented on patches/activate-cross-signing-and-secure-storage-react/matrix-react-sdk+3.63.0.patch
> +                     {_t(
est ce que cette modification de patch est nécessaire ?

2023-03-16 10:28 UTC, odelcroi approved these changes

2023-03-16 10:52 UTC, merged