Refactor patches.sh and add create script
tchapgouv/tchap-web-v4 pull request #479
Opened 2023-03-20 22:19 UTC by jdauphant

New script to merge, and new option to create patch.

2023-03-22 09:43 UTC, odelcroi requested changes
I think it is great. Currently we base our workflow with the file patches.json and the related scripts makePatch.ts, apply_patches.sh, checkPatchFile.js, we need to study how to merge the previous and new scripts.

2023-03-22 09:43 UTC, odelcroi commented on scripts/PATCHES.md
> +- Ensure you have Python installed on your system for the script to work correctly.
which version of python? no differnces?

2023-04-13 19:38 UTC, jdauphant commented on scripts/PATCHES.md
> +- Ensure you have Python installed on your system for the script to work correctly.
I have tried with python3

2023-05-04 07:56 UTC, odelcroi commented
closing for now. It would need more work to be compatible with how we work with yarn links

2023-05-04 07:56 UTC, closed without merging