Change confusing cle de session section in parameters
tchapgouv/tchap-web-v4 pull request #501
Opened 2023-03-27 15:47 UTC by aulamber

Answers issues:
- https://github.com/tchapgouv/tchap-web-v4/issues/465
- https://github.com/tchapgouv/tchap-web-v4/issues/463

Change screen:
<img width="666" alt="Capture d’écran 2023-03-27 à 17 46 42" src="https://user-images.githubusercontent.com/6305268/227993835-dafe8f5d-b14b-4b29-bc41-a57f8060b9ab.png">

Into:
<img width="668" alt="Capture d’écran 2023-03-27 à 17 46 57" src="https://user-images.githubusercontent.com/6305268/227993867-15690ff4-3771-4a84-897c-6ea0478f5b80.png">

And with advanced panel on:
<img width="671" alt="Capture d’écran 2023-03-27 à 17 47 02" src="https://user-images.githubusercontent.com/6305268/227993925-8325c6c7-3517-422e-b537-b4f0c8d93735.png">

2023-03-27 16:02 UTC, odelcroi commented
- clé de récupération should be code de récupération

2023-03-28 13:14 UTC, odelcroi commented on src/i18n/strings/tchap_translations.json
> +    "fr": "Attention ceci n’est pas votre clé de récuperation pour votre sauvegarde automatique.",
should be "code de récupération"

2023-03-28 13:29 UTC, odelcroi requested changes
update label

2023-03-29 14:25 UTC, aulamber commented on src/i18n/strings/tchap_translations.json
> +    "fr": "Attention ceci n’est pas votre clé de récuperation pour votre sauvegarde automatique.",
Done 👍

2023-03-29 16:03 UTC, odelcroi approved these changes

2023-03-29 23:53 UTC, merged