Add error message when domain is not allowed on Tchap
tchapgouv/tchap-web-v4 pull request #512
Opened 2023-03-30 13:47 UTC by odelcroi

Before : 
see ticket #460 

After : 
<img width="739" alt="Capture d’écran 2023-03-30 à 15 43 25" src="https://user-images.githubusercontent.com/4077729/228856380-00623cfa-4085-4333-bb7e-17ca4a21c813.png">

2023-03-30 14:44 UTC, odelcroi commented
- [x] What about external users that don't have an invit? test if they have the same message
- [ ] Yes, they do, maybe the message should talk to external users too
- [ ] maybe the link should go to https://tchap.beta.gouv.fr/

2023-03-30 15:22 UTC, areox-net requested changes
The message is ok.
However, I would not use the blue color for the link. It could just be an underlined part of the red text.

2023-03-31 09:27 UTC, areox-net approved these changes

2023-03-31 09:28 UTC, areox-net approved these changes

2023-03-31 09:28 UTC, areox-net approved these changes

2023-03-31 13:41 UTC, merged