Change bad wording reinit cross-signing
tchapgouv/tchap-web-v4 pull request #614
Opened 2023-06-05 09:48 UTC by aulamber

Cf. https://github.com/tchapgouv/tchap-web-v4/issues/609

2023-06-06 08:16 UTC, odelcroi commented on src/tchap/i18n/strings/tchap_translations.json
> +    "fr": "Détruire votre Code de Récupération ?",
Réinitialiser les clés de signature croisée

2023-06-06 08:17 UTC, odelcroi commented on src/tchap/i18n/strings/tchap_translations.json
> +    "fr": "La suppression du Code de Récupération est permanent. Tous les appareils que vous avez vérifiés vont voir des alertes de sécurité. Il est peu probable que ce soit ce que vous voulez faire,
Réinitialiser les clés de signature croisée...

Utiliser cette procédure uniquement si...

2023-06-06 08:17 UTC, odelcroi requested changes

2023-06-06 08:17 UTC, odelcroi commented on src/tchap/i18n/strings/tchap_translations.json
> +    "fr": "La suppression du Code de Récupération est permanent. Tous les appareils que vous avez vérifiés vont voir des alertes de sécurité. Il est peu probable que ce soit ce que vous voulez faire,
Cet écran est utilisé dans cette procédure : https://aide.tchap.beta.gouv.fr/fr/article/comment-verifier-tchap-mobile-android-iphone-depuis-la-messagerie-web-v4f9tk/

2023-06-06 10:03 UTC, aulamber commented on src/tchap/i18n/strings/tchap_translations.json
> +    "fr": "La suppression du Code de Récupération est permanent. Tous les appareils que vous avez vérifiés vont voir des alertes de sécurité. Il est peu probable que ce soit ce que vous voulez faire,
> Cet écran est utilisé dans cette procédure : https://aide.tchap.beta.gouv.fr/fr/article/comment-verifier-tchap-mobile-android-iphone-depuis-la-messagerie-web-v4f9tk/

Je peux donc changer le screenshot de l'article de FAQ à ça ?

<img width="749" alt="Capture d’écran 2023-06-06 à 12 04 14" src="https://github.com/tchapgouv/tchap-web-v4/assets/6305268/59eced39-5deb-4bdd-a9b3-d30ce46afd38">

2023-06-06 12:51 UTC, odelcroi commented on src/tchap/i18n/strings/tchap_translations.json
> +    "fr": "La suppression du Code de Récupération est permanent. Tous les appareils que vous avez vérifiés vont voir des alertes de sécurité. Il est peu probable que ce soit ce que vous voulez faire,
je changerai le bouton aussi pour qu'il coincide avec le titre

2023-06-07 09:30 UTC, aulamber commented on src/tchap/i18n/strings/tchap_translations.json
> +    "fr": "La suppression du Code de Récupération est permanent. Tous les appareils que vous avez vérifiés vont voir des alertes de sécurité. Il est peu probable que ce soit ce que vous voulez faire,
Changé à "Réinitialiser les clés de signature croisée"

2023-06-07 12:09 UTC, odelcroi approved these changes

2023-06-07 12:20 UTC, merged