Change forceLegacyIncomingRoomKeyVerification to false
tchapgouv/tchap-web-v4 pull request #615
Opened 2023-06-06 09:48 UTC by aulamber

Cf. https://github.com/tchapgouv/tchap-web-v4/issues/610

2023-06-06 12:49 UTC, odelcroi approved these changes

2023-06-06 15:28 UTC, odelcroi commented
(Ajout de tests dans la description)

2023-06-06 15:32 UTC, odelcroi reviewed
Ajouter une ligne de console.log pour vérifier que le listener n'est pas ajouté : https://github.com/tchapgouv/tchap-web-v4/blob/256199dbb76d69c4b71226563040126da1c5f974/patches/activate-cross-signing-and-secure-storage-react/matrix-react-sdk%2B3.71.1.patch#L32

2023-06-07 09:37 UTC, aulamber commented
> Ajouter une ligne de console.log pour vérifier que le listener n'est pas ajouté :
> 
> https://github.com/tchapgouv/tchap-web-v4/blob/256199dbb76d69c4b71226563040126da1c5f974/patches/activate-cross-signing-and-secure-storage-react/matrix-react-sdk%2B3.71.1.patch#L32

Done

2023-06-07 12:10 UTC, odelcroi requested changes

2023-06-07 12:10 UTC, odelcroi commented on patches/activate-cross-signing-and-secure-storage-react/matrix-react-sdk+3.71.1.patch
> ++            console.log('>>>> Enters forceLegacyIncomingRoomKeyVerification === true condition')
ajouter un tag :tchap: comme sur les autres logs et un message explicatif (titre de la PR?)

2023-06-08 09:59 UTC, aulamber commented
Erreur remontée par @NicolasBuquet : quand sur web on réinitialise la signature croisée en réinitialisant aussi le code de récupération, après avoir entré mon mot de passe, on a l'erreur suivante dans la console (rien à l'écran, tout est normal) :

Cache master cross-signing private key locally rageshake.ts:49:21
Cache self_signing cross-signing private key locally rageshake.ts:49:21
Cache user_signing cross-signing private key locally rageshake.ts:49:21
Cross-signing ready rageshake.ts:49:21
Error bootstrapping cross-signing Error: Invalid input, passphrase or recoveryKey need to be provided
    L SecurityManager.ts:93
    getSecretStorageKey SecurityManager.ts:174
    getSecretStorageKey EncryptionSetup.ts:325
    getSecretStorageKey secret-storage.ts:624
    store secret-storage.ts:519
    storeInSecretStorage CrossSigning.ts:198
    bootstrapCrossSigning index.ts:838
    bootstrapCrossSigning client.ts:2760
    Xt CrossSigningPanel.tsx:130
    onFinished CrossSigningPanel.tsx:156
    getCloseFn Modal.tsx:218
    Qt ConfirmDestroyCrossSigningDialog.tsx:29
    React 15

2023-06-12 13:15 UTC, NicolasBuquet commented
Le bug remonté ne semble en effet n'avoir aucun effet côté utilisateur. Il ne me semble donc pas prioritaire.

2023-06-13 15:19 UTC, odelcroi commented on patches/activate-cross-signing-and-secure-storage-react/matrix-react-sdk+3.71.1.patch
> ++            console.log('>>>> Enters forceLegacyIncomingRoomKeyVerification === true condition')
/
```suggestion
+            console.log(':tchap: activate the legacy incoming key verification')
```

2023-06-13 15:37 UTC, odelcroi approved these changes

2023-06-13 15:38 UTC, merged