Change error message when tchap service is down
tchapgouv/tchap-web-v4 pull request #636
Opened 2023-07-26 16:49 UTC by odelcroi

## room status bar

Before : 
<img width="667" alt="image" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/af9ebc7c-3ce8-467e-b560-dd920c185cab">

After : 
<img width="632" alt="Capture d’écran 2023-07-26 à 18 28 39" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/be52ff40-3893-4997-9006-787c94c1b173">

## Login 

Before : 

After :

2023-07-26 16:50 UTC, odelcroi commented
@areox-net @Caroline-lawson

2023-07-26 17:08 UTC, Caroline-lawson commented
Je suggère le texte suivant:

"La connexion à Tchap n'est pas possible pour le moment. Voir l'état du service
Les messages seront envoyés automatiquement dès que la connexion sera rétablie."

2023-07-27 11:40 UTC, Caroline-lawson commented
Sur l'écran de login, pourquoi on affiche "(err-03)" ?

On pourrait afficher "Voir l'état du service" à la ligne plutôt que à la suite de la phrase précédente ?

2023-07-27 11:59 UTC, NicolasBuquet requested changes, later dismissed
Dans tchap_translations.json :

- dans certaines phrases EN, Tchap est écrit "Tchape"
- dans 2 phrases d'erreur, il est marqué "Voir l'état du service", mais le lien n'est pas donné contrairement aux 3 phrases précédentes.

2023-07-27 12:04 UTC, Caroline-lawson commented
On peut mettre le lien vers l'état du service ?

2023-07-27 14:27 UTC, odelcroi commented
Merci, dans certains messages, je peux mettre le lien pour qu'il soit cliquable, dans d'autres, je ne peux pas, je dois mettre le lien pour qu'il soit copié-collable

2023-07-27 14:28 UTC, odelcroi commented
> Sur l'écran de login, pourquoi on affiche "(err-03)" ?
err-03 me permet de distinguer parmis toutes les erreurs ce qu'il se passe

2023-07-27 14:47 UTC, Caroline-lawson commented
Il y a souvent beaucoup d'erreurs en cours ? Faudrait voir comment on présente l'état du service.

2023-07-27 15:14 UTC, NicolasBuquet commented
Si tu corrige les 'Tchape" -> 'Tchap', je te valide la PR dans la foulée.

2023-07-28 09:15 UTC, areox-net commented
> > Sur l'écran de login, pourquoi on affiche "(err-03)" ?
> 
> Comme le message est le meme, err-03 me permet de distinguer l'erreur en détail

Il serait mieux d'avoir cela avant le lien. Avec toute la phrase "Voir l'état du service" en lien bleu.

La connexion à Tchap n'est pas possible pour le moment (Err-03).
**Voir l'état du service**

2023-07-28 10:10 UTC, Caroline-lawson commented
et si "voir l'état du service" renvoyait directement à la section de la page concernée ?

Je dis ça mais je ne sais pas quelle tête a la page d'état du service...

2023-07-31 07:34 UTC, odelcroi commented
la page de l'état du service : https://status.tchap.numerique.gouv.fr

2023-07-31 08:49 UTC, areox-net commented
C'est très bien. 
Dans la page login, dommage pour l'aller à la ligne sur le message en rouge pour très peu de charactères.

@Caroline-lawson Ca serait choquant d'avoir un message plus court avec une phrase sans article et verbe ? Genre, "Connexion à Tchap impossible pour le moment."
ou
"Connexion à Tchap momentanément impossible."

2023-08-01 13:35 UTC, mcalinghee commented
Test - OK
Juste un message "Your Tchap is misconfigured" mais non bloquant : 
![image](https://github.com/tchapgouv/tchap-web-v4/assets/3725676/9927632b-4aba-4ecd-9e37-d51929d89894)

2023-08-01 13:35 UTC, mcalinghee approved these changes

2023-08-01 13:38 UTC, areox-net approved these changes

2023-08-01 14:00 UTC, merged

2023-08-03 11:11 UTC, Caroline-lawson commented
> C'est très bien. Dans la page login, dommage pour l'aller à la ligne sur le message en rouge pour très peu de charactères.
> 
> @Caroline-lawson Ca serait choquant d'avoir un message plus court avec une phrase sans article et verbe ? Genre, "Connexion à Tchap impossible pour le moment." ou "Connexion à Tchap momentanément impossible."

Ah oui c'est bien ça

2023-08-03 11:12 UTC, Caroline-lawson commented
> Test - OK Juste un message "Your Tchap is misconfigured" mais non bloquant : ![image](https://user-images.githubusercontent.com/3725676/257530412-9927632b-4aba-4ecd-9e37-d51929d89894.png)

On peut supprimer le texte en anglais ?