Upgrade/element web v1.11.53
tchapgouv/tchap-web-v4 pull request #887
Opened 2024-02-05 14:53 UTC by estellecomment

2024-02-09 14:01 UTC, odelcroi commented on .github/labels.yml
we don't want those new labels in our repo

2024-02-09 14:23 UTC, odelcroi approved these changes
lgtm

2024-02-09 14:27 UTC, odelcroi commented on .github/labels.yml
removed

2024-02-09 14:29 UTC, odelcroi commented
I found a blocking bug : 
Go to parameters>about : panel closes with console error : 
<img width="587" alt="Capture d’écran 2024-02-09 à 15 26 15" src="https://github.com/tchapgouv/tchap-web-v4/assets/4077729/dd0ebbea-7aac-466b-ae99-e8126ef94859">

2024-02-09 14:30 UTC, odelcroi requested changes
blocking bug found, see comments

2024-02-13 13:46 UTC, estellecomment commented
Bug :     "Labs"/Experimental est affiché dans les settings :
![image](https://github.com/tchapgouv/tchap-web-v4/assets/911434/116caf79-6fcb-4a2c-b7fc-f1da67afb3cf)

(yavait pas un e2e test qui le checkait ??)

2024-02-14 08:13 UTC, odelcroi commented
> Bug : "Labs"/Experimental est affiché dans les settings : ![image](https://private-user-images.githubusercontent.com/911434/304430133-116caf79-6fcb-4a2c-b7fc-f1da67afb3cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4OTg2OTMsIm5iZiI6MTcwNzg5ODM5MywicGF0aCI6Ii85MTE0MzQvMzA0NDMwMTMzLTExNmNhZjc5LTZmY2ItNGEyYy1iN2ZjLWYxZGE2N2FmYjNjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQwODEzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2NmOWRhODNmM2U1M2I4ODUxYWVkZDkyNTEwYzBlMWRhZTIwZThmN2RkMzk5ZWViNzk4OTAxYmMxMmQ5ZjJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zmbG0tRt_-ZN-AJpYhSSamGwG-QW5eiUCnPQcDwkKu0)
> 
> (yavait pas un e2e test qui le checkait ??)

Je ne le vois pas dans la review app, où l'as tu vu? Sinon on merge et on fixe après, ca semble pas bloquant

2024-02-14 11:27 UTC, merged